version: '3'
services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./project:/var/www/html
    depends_on:
      - mysql
    environment:
      COMPOSER_PROCESS_TIMEOUT: 600

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password_api_slim_framework'
      MYSQL_DATABASE: 'api_slim_framework_com_docker'
      MYSQL_PASSWORD: 'password_api_slim_framework'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'password_api_slim_framework'